def app_store_connect_key
  key_content = ENV["ASC_KEY_P8"]
  is_base64 = !(key_content&.include?("BEGIN PRIVATE KEY"))

  app_store_connect_api_key(
    key_id: ENV["ASC_KEY_ID"],
    issuer_id: ENV["ASC_ISSUER_ID"],
    key_content: key_content,
    is_key_content_base64: is_base64
  )
end

platform :ios do
  desc "Build and upload to TestFlight"
  lane :testflight do |options|
    if options[:version]
      increment_version_number(version_number: options[:version])
    end

    if options[:build_number]
      increment_build_number(build_number: options[:build_number])
    else
      increment_build_number
    end

    gym(
      scheme: "Renewo",
      export_method: "app-store"
    )

    pilot(api_key: app_store_connect_key)
  end
end
